version: '3.8'
services:
  nginx:
    image: nginx:1.19.6
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - network
    restart: always
  mariadb:
    image: mariadb:10.5.8
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network
    restart: always
networks:
  network:
volumes:
  db_data:
  wordpress_volume:
