version: '3.8'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - network
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./requirements/wordpress/conf/wp-config.php:/var/www/html/wp-config.php
    networks:
      - network
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
      MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network
    restart: always
networks:
  network:
volumes:
  db_data:
  wordpress_volume:
