version: '3'
services:

  db:
    build: ./requirements/mariadb/Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  web:
    build: ./path/to/webapp
    image: web
    ports:
      - "8000:8000"
    depends_on:
      - db